# Generated by Django 5.2 on 2025-04-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
