# Generated by Django 5.2 on 2025-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_active_code',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
