# Generated by Django 5.2 on 2025-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0005_remove_user_email_active_code_user_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='09100000000'),
        ),
    ]
